### ISSUE TITLE
about coremark-2-iteration.bin and linux.bin

### ISSUE THREAD

**Issue by janboeye** [XS-MLVP/env-xs-ov-00-bpu#4]
hi, 

After setting up the environment and change config.py , I noticed that the branch instructon number for coremark-2-iteration.bin is unexpectedly low. Could you help me verify if coremark-2-iteration.bin and linux.bin can run correctly?

Thanks

**Comment by yaozhicheng** [comment]
If it's just a simple predictor (like uFTB), its accuracy is inherently low.

**Comment by janboeye** [comment]
en, I'm not talking about low accuracy, but low instruction count.
I changed max_cycle from 10000 to 1000000, but the log always shows [Conditional Branches]
Total: 210, Correct: 155, Accuracy: 0.7380952380952381, I suspect that _NemuBR has an error in executing coremark.

**Comment by Miical** [comment]
> Sorry, my words are ambiguous. I didn't say the accuracy is low, but low instruction count. I changed max_cycle from 10000 to 1000000, but the log always shows [Conditional Branches] Total: 210, Correct: 155, Accuracy: 0.7380952380952381, I suspect that _NemuBR has an error in executing coremark.

Hello, thank you for pointing this out, this problem exists. This problem occurs because in the branch Trace provided by NEMU, the execution of branch Trace is inconsistent due to other factors, such as interruption or missing detection. The next branch address obtained by the environment is before the current PC, so it can never be executed. A new commit has just been created so that the environment can detect that this is happening and continue to execute correctly. You can update your code and run it again.
